apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: test-rs
  labels:
    app: test-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-rs
  template:
    metadata:
      labels:
        app: test-rs
    spec:
      containers:
      - name: nginx
        image: nginx
